[workspace]
members = [
    "crates/chat-rollup",
    "crates/rollup-cli",
    "crates/rollup-core",
    "tools/protobuf-compiler",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
prost = "0.12.6"
